title: Machine Learning for Engineering and Science Applications.
description: Course given by Prof. Balaji Srinivasan and Prof Ganapathy Krishnamurthy, Indian Institute of Technology Chennai.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
