title: Machine Learning
description: Course given by Prof. Balaji Srinivasan and Prof Ganapathy Krishnamurthy, Indian Institute of Technology Chennai.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
